# Importing the main cvs file

In [1]:
import pandas as pd

In [2]:
Pre_Crash = pd.read_csv('/Users/shilpa/Downloads/2016_ETL_distracted.csv')
Pre_Crash

,statenum,casenum,vnumber,crashtype,dridistract,dridistract.1,driavoidmanvr,drivisobs
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,48.0,1.0,1.0,86.0,0.0,0.0,98.0,0.0
2,48.0,1.0,2.0,87.0,0.0,0.0,98.0,0.0
3,48.0,1.0,3.0,98.0,0.0,0.0,0.0,0.0
4,48.0,2.0,1.0,6.0,0.0,0.0,98.0,0.0
...,...,...,...,...,...,...,...,...
5322,48.0,3525.0,2.0,49.0,0.0,0.0,98.0,0.0
5323,48.0,3526.0,1.0,24.0,0.0,0.0,98.0,0.0
5324,48.0,3526.0,2.0,25.0,0.0,0.0,98.0,0.0
5325,48.0,3527.0,1.0,28.0,0.0,0.0,98.0,0.0
5326,48.0,3527.0,2.0,29.0,0.0,0.0,98.0,0.0

# Renaming the columns

In [3]:
Rename_Pre_Crash = Pre_Crash.rename(columns={'statenum': 'StateName', 
                         'casenum': 'CaseNo', 
                         'vnumber': 'VehicleNo', 
                         'crashtype': 'CrashType',
                        'dridistract': 'FirstDistraction',
                         'dridistract.1': 'SecondDistraction',
                        'driavoidmanvr': "DriverAction",
                        'drivisobs': 'ObscuredVision'})
Rename_Pre_Crash

,StateName,CaseNo,VehicleNo,CrashType,FirstDistraction,SecondDistraction,DriverAction,ObscuredVision
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,48.0,1.0,1.0,86.0,0.0,0.0,98.0,0.0
2,48.0,1.0,2.0,87.0,0.0,0.0,98.0,0.0
3,48.0,1.0,3.0,98.0,0.0,0.0,0.0,0.0
4,48.0,2.0,1.0,6.0,0.0,0.0,98.0,0.0
...,...,...,...,...,...,...,...,...
5322,48.0,3525.0,2.0,49.0,0.0,0.0,98.0,0.0
5323,48.0,3526.0,1.0,24.0,0.0,0.0,98.0,0.0
5324,48.0,3526.0,2.0,25.0,0.0,0.0,98.0,0.0
5325,48.0,3527.0,1.0,28.0,0.0,0.0,98.0,0.0
5326,48.0,3527.0,2.0,29.0,0.0,0.0,98.0,0.0

In [5]:
Rename_Pre_Crash.dropna().astype(int)

,StateName,CaseNo,VehicleNo,CrashType,FirstDistraction,SecondDistraction,DriverAction,ObscuredVision
1,48,1,1,86,0,0,98,0
2,48,1,2,87,0,0,98,0
3,48,1,3,98,0,0,0,0
4,48,2,1,6,0,0,98,0
5,48,3,1,1,0,0,98,0
...,...,...,...,...,...,...,...,...
5322,48,3525,2,49,0,0,98,0
5323,48,3526,1,24,0,0,98,0
5324,48,3526,2,25,0,0,98,0
5325,48,3527,1,28,0,0,98,0
5326,48,3527,2,29,0,0,98,0

# Importing Crash Type Code Definition file

In [6]:
crash_type = pd.read_csv('/Users/shilpa/Desktop/Crash_Type_Code Definitions.csv')
crash_type.head()

   ID                                        Def
0   0                               (0)No Impact
1   1                          (1)Drive Off Road
2   2                   (2)Control/Traction Loss
3   3  (3)Avoid Collision With Veh., Ped., Anim.
4   4                         (4)Specifics Other

In [38]:
Merge_Crash = Rename_Pre_Crash.merge(crash_type, left_on='CrashType', right_on='ID')
Merge_Crash = Merge_Crash.drop([ 'ID', 'CrashType'], axis=1)
Merge_Crash = Merge_Crash.rename(columns={"Def": "CrashType"})
Merge_Crash['CrashType'] = [item.split(")", 1)[1] for item in Merge_Crash['CrashType']]
Merge_Crash = Merge_Crash.rename(columns={"Def": "CrashType"})
Merge_Crash

,StateName,CaseNo,VehicleNo,FirstDistraction,SecondDistraction,DriverAction,ObscuredVision,CrashType
0,48.0,1.0,1.0,0.0,0.0,98.0,0.0,Striking From The Right
1,48.0,48.0,2.0,0.0,0.0,0.0,0.0,Striking From The Right
2,48.0,89.0,1.0,0.0,0.0,98.0,0.0,Striking From The Right
3,48.0,92.0,2.0,0.0,0.0,98.0,0.0,Striking From The Right
4,48.0,122.0,2.0,0.0,0.0,98.0,0.0,Striking From The Right
...,...,...,...,...,...,...,...,...
5321,48.0,3521.0,1.0,6.0,6.0,92.0,0.0,"Avoid Collision With Veh., Ped., Anim."
5322,48.0,2937.0,1.0,0.0,0.0,98.0,0.0,Specifics Unknown
5323,48.0,2937.0,2.0,0.0,0.0,98.0,0.0,Specifics Unknown
5324,48.0,3337.0,1.0,93.0,93.0,98.0,0.0,Specifics Unknown
5325,48.0,3337.0,2.0,93.0,93.0,98.0,0.0,Specifics Unknown

# Importing Distraction1 and Distraction 2

In [39]:
distracted_by = pd.read_csv('/Users/shilpa/Library/Containers/com.microsoft.Excel/Data/Desktop/Driver_distracted_by_Code Definitions.csv')
distracted_by.head()

   ID                                              Def
0   0                                (0)Not Distracted
1   1                        (1)Looked But Did Not See
2   3                          (3)By Other Occupant(s)
3   4                 (4)By A Moving Object In Vehicle
4   5  (5)While Talking Or Listening To Cellular Phone

In [40]:
Merge_First_Distraction = Merge_Crash.merge(distracted_by, left_on='FirstDistraction', right_on='ID')
Merge_First_Distraction = Merge_First_Distraction.drop([ 'ID', 'FirstDistraction'], axis=1)
Merge_First_Distraction = Merge_First_Distraction.rename(columns={"Def": "FirstDistraction"})
Merge_First_Distraction['FirstDistraction'] = [item.split(")", 1)[1] for item in Merge_First_Distraction['FirstDistraction']]
Merge_First_Distraction = Merge_First_Distraction.rename(columns={"Def": "FirstDistraction"})
Merge_First_Distraction

,StateName,CaseNo,VehicleNo,SecondDistraction,DriverAction,ObscuredVision,CrashType,FirstDistraction
0,48.0,1.0,1.0,0.0,98.0,0.0,Striking From The Right,Not Distracted
1,48.0,48.0,2.0,0.0,0.0,0.0,Striking From The Right,Not Distracted
2,48.0,89.0,1.0,0.0,98.0,0.0,Striking From The Right,Not Distracted
3,48.0,92.0,2.0,0.0,98.0,0.0,Striking From The Right,Not Distracted
4,48.0,122.0,2.0,0.0,98.0,0.0,Striking From The Right,Not Distracted
...,...,...,...,...,...,...,...,...
5321,48.0,606.0,2.0,98.0,0.0,0.0,Slower,Other Distraction
5322,48.0,880.0,1.0,98.0,0.0,0.0,Stopped,Other Distraction
5323,48.0,3474.0,1.0,19.0,0.0,0.0,Stopped,Careless/Inattentive
5324,48.0,671.0,1.0,14.0,0.0,0.0,Decelerating (Slowing),Smoking Related
5325,48.0,3018.0,2.0,96.0,99.0,99.0,Straight Ahead On Left,Not Reported

In [41]:
Merge_Second_Distraction = Merge_First_Distraction.merge(distracted_by, left_on='SecondDistraction', right_on='ID')
Merge_Second_Distraction = Merge_Second_Distraction.drop([ 'ID', 'SecondDistraction'], axis=1)
Merge_Second_Distraction = Merge_Second_Distraction.rename(columns={"Def": "SecondDistraction"})
Merge_Second_Distraction['SecondDistraction'] = [item.split(")", 1)[1] for item in Merge_Second_Distraction['SecondDistraction']]
Merge_Second_Distraction = Merge_Second_Distraction.rename(columns={"Def": "SecondDistraction"})
Merge_Second_Distraction.head()

,StateName,CaseNo,VehicleNo,DriverAction,ObscuredVision,CrashType,FirstDistraction,SecondDistraction
0,48.0,1.0,1.0,98.0,0.0,Striking From The Right,Not Distracted,Not Distracted
1,48.0,48.0,2.0,0.0,0.0,Striking From The Right,Not Distracted,Not Distracted
2,48.0,89.0,1.0,98.0,0.0,Striking From The Right,Not Distracted,Not Distracted
3,48.0,92.0,2.0,98.0,0.0,Striking From The Right,Not Distracted,Not Distracted
4,48.0,122.0,2.0,98.0,0.0,Striking From The Right,Not Distracted,Not Distracted

In [43]:
DriverAction = pd.read_csv('/Users/shilpa/Desktop/Driver_manuvered_to_avoid_Code Definitions.csv')
DriverAction.head()

   ID                                                Def
0   0                (0)Driver Did Not Maneuver To Avoid
1   1                                          (1)Object
2   2  (2)Poor Road Conditions (Puddle, Ice, Pothole,...
3   3                                     (3)Live Animal
4   4                                   (4)Motor Vehicle

# Merge Driver Action

In [52]:
Merge_DriverAction = Merge_Second_Distraction.merge(DriverAction, left_on='DriverAction', right_on='ID')
Merge_DriverAction = Merge_DriverAction.drop([ 'ID', 'DriverAction'], axis=1)
Merge_DriverAction = Merge_DriverAction.rename(columns={"Def": "DriverAction"})
Merge_DriverAction['DriverAction'] = [item.split(")", 1)[1] for item in Merge_DriverAction['DriverAction']]
Merge_DriverAction = Merge_DriverAction.rename(columns={"Def": "DriverAction"})
Merge_DriverAction.head()

,StateName,CaseNo,VehicleNo,ObscuredVision,CrashType,FirstDistraction,SecondDistraction,DriverAction
0,48.0,1.0,1.0,0.0,Striking From The Right,Not Distracted,Not Distracted,Not Reported
1,48.0,89.0,1.0,0.0,Striking From The Right,Not Distracted,Not Distracted,Not Reported
2,48.0,92.0,2.0,0.0,Striking From The Right,Not Distracted,Not Distracted,Not Reported
3,48.0,122.0,2.0,0.0,Striking From The Right,Not Distracted,Not Distracted,Not Reported
4,48.0,188.0,2.0,0.0,Striking From The Right,Not Distracted,Not Distracted,Not Reported

# Create Unique ID, Renumber Case and Vehicle Number

In [54]:
Merge_DriverAction['StateName'] = Merge_DriverAction['StateName'].astype(int)
Merge_DriverAction
Merge_DriverAction['StateName'] = Merge_DriverAction['StateName'].replace(48, 'Texas')
Merge_DriverAction

,StateName,CaseNo,VehicleNo,ObscuredVision,CrashType,FirstDistraction,SecondDistraction,DriverAction
0,Texas,1.0,1.0,0.0,Striking From The Right,Not Distracted,Not Distracted,Not Reported
1,Texas,89.0,1.0,0.0,Striking From The Right,Not Distracted,Not Distracted,Not Reported
2,Texas,92.0,2.0,0.0,Striking From The Right,Not Distracted,Not Distracted,Not Reported
3,Texas,122.0,2.0,0.0,Striking From The Right,Not Distracted,Not Distracted,Not Reported
4,Texas,188.0,2.0,0.0,Striking From The Right,Not Distracted,Not Distracted,Not Reported
...,...,...,...,...,...,...,...,...
5321,Texas,2265.0,2.0,95.0,Specifics Other,No Driver Present/Unknown If Driver Present,No Driver Present/Unknown If Driver Present,No Driver Present/Unknown If Driver Present
5322,Texas,2516.0,1.0,95.0,Specifics Other,No Driver Present/Unknown If Driver Present,No Driver Present/Unknown If Driver Present,No Driver Present/Unknown If Driver Present
5323,Texas,2734.0,2.0,95.0,Specifics Other,No Driver Present/Unknown If Driver Present,No Driver Present/Unknown If Driver Present,No Driver Present/Unknown If Driver Present
5324,Texas,3133.0,2.0,95.0,Specifics Other,No Driver Present/Unknown If Driver Present,No Driver Present/Unknown If Driver Present,No Driver Present/Unknown If Driver Present
5325,Texas,1163.0,2.0,95.0,Specifics Other,No Driver Present/Unknown If Driver Present,No Driver Present/Unknown If Driver Present,No Driver Present/Unknown If Driver Present

In [59]:
Merge_DriverAction['CaseNo'] = [str(int(CaseNo)).zfill(4) for CaseNo in Merge_DriverAction['CaseNo']]
Merge_DriverAction['VehicleNo'] = [str(int(VehicleNo)).zfill(4) for VehicleNo in Merge_DriverAction['VehicleNo']]
Merge_DriverAction["ID"] = Merge_DriverAction['CaseNo'] + Merge_DriverAction['VehicleNo']
Merge_DriverAction["ID"]

0       00010001
1       00890001
2       00920002
3       01220002
4       01880002
          ...
5321    22650002
5322    25160001
5323    27340002
5324    31330002
5325    11630002
Name: ID, Length: 5326, dtype: object

In [62]:
Pre_Crash_Final = pd.DataFrame(Pre_Crash_Final)
Pre_Crash_Final  = Pre_Crash_Final [["StateName", "ID", "CaseNo", "VehicleNo", "CrashType", "FirstDistraction", "SecondDistraction","DriverAction"]]
Pre_Crash_Final.head()

,StateName,ID,CaseNo,VehicleNo,CrashType,FirstDistraction,SecondDistraction,DriverAction
0,Texas,00010001,0001,0001,Striking From The Right,Not Distracted,Not Distracted,Not Reported
1,Texas,00890001,0089,0001,Striking From The Right,Not Distracted,Not Distracted,Not Reported
2,Texas,00920002,0092,0002,Striking From The Right,Not Distracted,Not Distracted,Not Reported
3,Texas,01220002,0122,0002,Striking From The Right,Not Distracted,Not Distracted,Not Reported
4,Texas,01880002,0188,0002,Striking From The Right,Not Distracted,Not Distracted,Not Reported

# The End