In [48]:
import pandas as pd

In [49]:
df = pd.read_csv('/Users/shilpa/Downloads/2016_ETL_distracted.csv')

In [50]:
df1 = df.rename(columns={'statenum': 'State Name', 
                         'casenum': 'CaseNo', 
                         'vnumber': 'VehicleNo', 
                         'crashtype': 'CrashType',
                        'dridistract': 'Distracted By',
                        'driavoidmanvr': "Driver's Action",
                        'drivisobs': 'Obscured Vision'})
df1

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,48.0,1.0,1.0,86.0,0.0,98.0,0.0
2,48.0,1.0,2.0,87.0,0.0,98.0,0.0
3,48.0,1.0,3.0,98.0,0.0,0.0,0.0
4,48.0,2.0,1.0,6.0,0.0,98.0,0.0
...,...,...,...,...,...,...,...
5329,48.0,3525.0,2.0,49.0,0.0,98.0,0.0
5330,48.0,3526.0,1.0,24.0,0.0,98.0,0.0
5331,48.0,3526.0,2.0,25.0,0.0,98.0,0.0
5332,48.0,3527.0,1.0,28.0,0.0,98.0,0.0
5333,48.0,3527.0,2.0,29.0,0.0,98.0,0.0

In [51]:
df1.dropna()

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision
1,48.0,1.0,1.0,86.0,0.0,98.0,0.0
2,48.0,1.0,2.0,87.0,0.0,98.0,0.0
3,48.0,1.0,3.0,98.0,0.0,0.0,0.0
4,48.0,2.0,1.0,6.0,0.0,98.0,0.0
5,48.0,3.0,1.0,1.0,0.0,98.0,0.0
...,...,...,...,...,...,...,...
5329,48.0,3525.0,2.0,49.0,0.0,98.0,0.0
5330,48.0,3526.0,1.0,24.0,0.0,98.0,0.0
5331,48.0,3526.0,2.0,25.0,0.0,98.0,0.0
5332,48.0,3527.0,1.0,28.0,0.0,98.0,0.0
5333,48.0,3527.0,2.0,29.0,0.0,98.0,0.0

In [52]:
 df1.dtypes

State Name         float64
CaseNo             float64
VehicleNo          float64
CrashType          float64
Distracted By      float64
Driver's Action    float64
Obscured Vision    float64
dtype: object

In [53]:
df2 = df1.dropna()
df2.head()

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision
1,48.0,1.0,1.0,86.0,0.0,98.0,0.0
2,48.0,1.0,2.0,87.0,0.0,98.0,0.0
3,48.0,1.0,3.0,98.0,0.0,0.0,0.0
4,48.0,2.0,1.0,6.0,0.0,98.0,0.0
5,48.0,3.0,1.0,1.0,0.0,98.0,0.0

In [54]:
 df3 = df2.astype(int)

In [55]:
df3.head()

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision
1,48,1,1,86,0,98,0
2,48,1,2,87,0,98,0
3,48,1,3,98,0,0,0
4,48,2,1,6,0,98,0
5,48,3,1,1,0,98,0

In [56]:
df3['CaseNo'] = [str(int(CaseNo)).zfill(4) for CaseNo in df3['CaseNo']]
df3['VehicleNo'] = [str(int(VehicleNo)).zfill(4) for VehicleNo in df3['VehicleNo']]
df3["ID"] = df3['CaseNo'] + df3['VehicleNo']
df3["ID"]

1       00010001
2       00010002
3       00010003
4       00020001
5       00030001
          ...
5329    35250002
5330    35260001
5331    35260002
5332    35270001
5333    35270002
Name: ID, Length: 5333, dtype: object

In [57]:
df3

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision,ID
1,48,0001,0001,86,0,98,0,00010001
2,48,0001,0002,87,0,98,0,00010002
3,48,0001,0003,98,0,0,0,00010003
4,48,0002,0001,6,0,98,0,00020001
5,48,0003,0001,1,0,98,0,00030001
...,...,...,...,...,...,...,...,...
5329,48,3525,0002,49,0,98,0,35250002
5330,48,3526,0001,24,0,98,0,35260001
5331,48,3526,0002,25,0,98,0,35260002
5332,48,3527,0001,28,0,98,0,35270001
5333,48,3527,0002,29,0,98,0,35270002

In [58]:
df3

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision,ID
1,48,0001,0001,86,0,98,0,00010001
2,48,0001,0002,87,0,98,0,00010002
3,48,0001,0003,98,0,0,0,00010003
4,48,0002,0001,6,0,98,0,00020001
5,48,0003,0001,1,0,98,0,00030001
...,...,...,...,...,...,...,...,...
5329,48,3525,0002,49,0,98,0,35250002
5330,48,3526,0001,24,0,98,0,35260001
5331,48,3526,0002,25,0,98,0,35260002
5332,48,3527,0001,28,0,98,0,35270001
5333,48,3527,0002,29,0,98,0,35270002

In [59]:
crash_type = pd.read_csv('/Users/shilpa/Desktop/Crash_Type_Code Definitions.csv')

In [60]:
crash_type["Def"].iloc[0]

'(0)No Impact'

In [69]:
df3["CrashType"].iloc[1] = crash_type["ID"][8]

In [70]:
crash_type.loc[1]

ID                     1
Def    (1)Drive Off Road
Name: 1, dtype: object

In [71]:
crash_type.loc[crash_type['ID']==86,['Def']]

                            Def
83  (86)Striking From The Right

In [72]:
crash_type.astype(str)

    ID                                        Def
0    0                               (0)No Impact
1    1                          (1)Drive Off Road
2    2                   (2)Control/Traction Loss
3    3  (3)Avoid Collision With Veh., Ped., Anim.
4    4                         (4)Specifics Other
..  ..                                        ...
88  91                      (91)Specifics Unknown
89  92                           (92)Backing Veh.
90  93                          (93)Other Vehicle
91  98                       (98)Other Crash Type
92  99                                (99)Unknown

[93 rows x 2 columns]

In [73]:
int(crash_type.index[crash_type['ID'] == 0][0])

0

In [74]:
crash_type["Def"].iloc[0]

'(0)No Impact'

In [75]:
import re
df3 = df2.dropna()
for i in range (0, 5336):
    idx = int(crash_type.index[crash_type['ID'] == df3["CrashType"].iloc[i]][0])
    a = crash_type["Def"].iloc[idx]
    df3["CrashType"].iloc[i] = re.sub(r'\(\d+\)',"", a)
print(df3)

IndexError: single positional indexer is out-of-bounds

In [76]:

 df3 
#for i in range (0, 5336):
#    idx = int(crash_type.index[crash_type['ID'] == df3["CrashType"].iloc[i]][0])
#    a = crash_type["Def"].iloc[idx] = df3["CrashType"].iloc[i]
df3

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision
1,48.0,1.0,1.0,Striking From The Right,0.0,98.0,0.0
2,48.0,1.0,2.0,Struck On The Right,0.0,98.0,0.0
3,48.0,1.0,3.0,Other Crash Type,0.0,0.0,0.0
4,48.0,2.0,1.0,Drive Off Road,0.0,98.0,0.0
5,48.0,3.0,1.0,Drive Off Road,0.0,98.0,0.0
...,...,...,...,...,...,...,...
5329,48.0,3525.0,2.0,Specifics Unknown,0.0,98.0,0.0
5330,48.0,3526.0,1.0,Slower,0.0,98.0,0.0
5331,48.0,3526.0,2.0,"Slower, Going Straight",0.0,98.0,0.0
5332,48.0,3527.0,1.0,Decelerating (Slowing),0.0,98.0,0.0
5333,48.0,3527.0,2.0,"Decelerating (Slowing), Going Straight",0.0,98.0,0.0

In [81]:
df_A = pd.DataFrame(df3)
df_A

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision
1,48.0,1.0,1.0,Striking From The Right,0.0,98.0,0.0
2,48.0,1.0,2.0,Struck On The Right,0.0,98.0,0.0
3,48.0,1.0,3.0,Other Crash Type,0.0,0.0,0.0
4,48.0,2.0,1.0,Drive Off Road,0.0,98.0,0.0
5,48.0,3.0,1.0,Drive Off Road,0.0,98.0,0.0
...,...,...,...,...,...,...,...
5329,48.0,3525.0,2.0,Specifics Unknown,0.0,98.0,0.0
5330,48.0,3526.0,1.0,Slower,0.0,98.0,0.0
5331,48.0,3526.0,2.0,"Slower, Going Straight",0.0,98.0,0.0
5332,48.0,3527.0,1.0,Decelerating (Slowing),0.0,98.0,0.0
5333,48.0,3527.0,2.0,"Decelerating (Slowing), Going Straight",0.0,98.0,0.0

In [79]:
distracted_by = pd.read_csv('/Users/shilpa/Library/Containers/com.microsoft.Excel/Data/Desktop/Driver_distracted_by_Code Definitions.csv')
distracted_by

    ID                                                Def
0    0                                  (0)Not Distracted
1    1                          (1)Looked But Did Not See
2    3                            (3)By Other Occupant(s)
3    4                   (4)By A Moving Object In Vehicle
4    5    (5)While Talking Or Listening To Cellular Phone
5    6               (6)While Manipulating Cellular Phone
6    7             (7)Adjusting Audio Or Climate Controls
7    9  (9)While Using Other Component/Controls Integr...
8   10  (10)While Using Or Reaching For Device/Object ...
9   12  (12)Distracted By Outside Person, Object Or Event
10  13                             (13)Eating Or Drinking
11  14                                (14)Smoking Related
12  15                   (15)Other Cellular Phone Related
13  16    (16)No Driver Present/Unknown If Driver Present
14  17                        (17)Distraction/Inattention
15  18                           (18)Distraction/Careless
16  19                           (19)Careless/Inattentive
17  92      (92)Distraction (Distracted), Details Unknown
18  93     (93)Inattention (Inattentive), Details Unknown
19  96                                   (96)Not Reported
20  97                 (97)Lost In Thought / Day Dreaming
21  98                              (98)Other Distraction
22  99                          (99)Unknown If Distracted

In [80]:
distracted_by["Def"].iloc[0]

'(0)Not Distracted'

In [82]:
import re
df_A
for i in range (0, 5336):
    idx = int(distracted_by.index[distracted_by['ID'] == df_A["Distracted By"].iloc[i]][0])
    a = distracted_by["Def"].iloc[idx]
    df_A["Distracted By"].iloc[i] = re.sub(r'\(\d+\)',"", a)
print(df_A)

IndexError: single positional indexer is out-of-bounds

In [83]:
df_A 
#for i in range (0, 5336):
    #idx = int(distracted_by.index[distracted_by['ID'] == df_A["Distracted By"].iloc[i]][0])
    #distracted_by["Def"].iloc[idx] = df_A["Distracted By"].iloc[i] 
#df_A

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision
1,48.0,1.0,1.0,Striking From The Right,Not Distracted,98.0,0.0
2,48.0,1.0,2.0,Struck On The Right,Not Distracted,98.0,0.0
3,48.0,1.0,3.0,Other Crash Type,Not Distracted,0.0,0.0
4,48.0,2.0,1.0,Drive Off Road,Not Distracted,98.0,0.0
5,48.0,3.0,1.0,Drive Off Road,Not Distracted,98.0,0.0
...,...,...,...,...,...,...,...
5329,48.0,3525.0,2.0,Specifics Unknown,Not Distracted,98.0,0.0
5330,48.0,3526.0,1.0,Slower,Not Distracted,98.0,0.0
5331,48.0,3526.0,2.0,"Slower, Going Straight",Not Distracted,98.0,0.0
5332,48.0,3527.0,1.0,Decelerating (Slowing),Not Distracted,98.0,0.0
5333,48.0,3527.0,2.0,"Decelerating (Slowing), Going Straight",Not Distracted,98.0,0.0

In [84]:
df_B = pd.DataFrame(df_A)
df_B

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision
1,48.0,1.0,1.0,Striking From The Right,Not Distracted,98.0,0.0
2,48.0,1.0,2.0,Struck On The Right,Not Distracted,98.0,0.0
3,48.0,1.0,3.0,Other Crash Type,Not Distracted,0.0,0.0
4,48.0,2.0,1.0,Drive Off Road,Not Distracted,98.0,0.0
5,48.0,3.0,1.0,Drive Off Road,Not Distracted,98.0,0.0
...,...,...,...,...,...,...,...
5329,48.0,3525.0,2.0,Specifics Unknown,Not Distracted,98.0,0.0
5330,48.0,3526.0,1.0,Slower,Not Distracted,98.0,0.0
5331,48.0,3526.0,2.0,"Slower, Going Straight",Not Distracted,98.0,0.0
5332,48.0,3527.0,1.0,Decelerating (Slowing),Not Distracted,98.0,0.0
5333,48.0,3527.0,2.0,"Decelerating (Slowing), Going Straight",Not Distracted,98.0,0.0

In [86]:
DriverAction = pd.read_csv('/Users/shilpa/Desktop/Driver_manuvered_to_avoid_Code Definitions.csv')
DriverAction

   ID                                                Def
0   0                (0)Driver Did Not Maneuver To Avoid
1   1                                          (1)Object
2   2  (2)Poor Road Conditions (Puddle, Ice, Pothole,...
3   3                                     (3)Live Animal
4   4                                   (4)Motor Vehicle
5   5  (5)Pedestrian, Pedalcyclist Or Other Non-Motorist
6  92              (92)Phantom/Non-Contact Motor Vehicle
7  95    (95)No Driver Present/Unknown If Driver Present
8  98                                   (98)Not Reported
9  99                                        (99)Unknown

In [87]:
DriverAction["Def"].iloc[0]

'(0)Driver Did Not Maneuver To Avoid'

In [90]:
import re
df_B
for i in range (0, 5336):
    idx = int(DriverAction.index[DriverAction['ID'] == df_B["Driver's Action"].iloc[i]][0])
    a = DriverAction["Def"].iloc[idx]
    df_B["Driver's Action"].iloc[i] = re.sub(r'\(\d+\)',"", a)
print(df_B)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [91]:
df_B
#for i in range (0, 5336):
    #idx = int(DriverAction.index[dDriverAction['ID'] == df_B["Driver's Action"].iloc[i]][0])
    #DriverAction["Def"].iloc[idx] = df_B["Driver's Action"].iloc[i] 
#df_B

,State Name,CaseNo,VehicleNo,CrashType,Distracted By,Driver's Action,Obscured Vision
1,48.0,1.0,1.0,Striking From The Right,Not Distracted,Not Reported,0.0
2,48.0,1.0,2.0,Struck On The Right,Not Distracted,Not Reported,0.0
3,48.0,1.0,3.0,Other Crash Type,Not Distracted,Driver Did Not Maneuver To Avoid,0.0
4,48.0,2.0,1.0,Drive Off Road,Not Distracted,Not Reported,0.0
5,48.0,3.0,1.0,Drive Off Road,Not Distracted,Not Reported,0.0
...,...,...,...,...,...,...,...
5329,48.0,3525.0,2.0,Specifics Unknown,Not Distracted,Not Reported,0.0
5330,48.0,3526.0,1.0,Slower,Not Distracted,Not Reported,0.0
5331,48.0,3526.0,2.0,"Slower, Going Straight",Not Distracted,Not Reported,0.0
5332,48.0,3527.0,1.0,Decelerating (Slowing),Not Distracted,Not Reported,0.0
5333,48.0,3527.0,2.0,"Decelerating (Slowing), Going Straight",Not Distracted,Not Reported,0.0